version: "3.8"
services:
  feims:
    build: .
    ports: 
      - 3000:3000
    environment: 
      DB_URL: mongodb://mongo:27017/feims
  mongo:
    image: mongo:4.4.6-bionic
    restart: always
    ports:
      - 27017:27017
  mongo-express:
    image : mongo-express:1.0.0-alpha
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo